export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const UPDATE_PAGE = 'TOGGLE_PAGE';
export const FETCH_CURRENCIES_SUCCESS = 'FETCH_CURRENCIES_SUCCESS';
export const FETCH_CURRENCIES_FAILURE = 'FETCH_CURRENCIES_FAILURE';
